services:
  server:
    container_name: performance_demo_server
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    networks:
      - performance-demo-net
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '1.0'
    environment:
      PORT: 8080

  performance-test:
    container_name: performance_demo_tester
    build:
      context: ../
      dockerfile: ./docker/tester/Dockerfile
    networks:
      - performance-demo-net
    environment:
      PORT: 8080
      FIBONACCI_SEQUENCE_NUMBER: 33
    stdin_open: true
    tty: true
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ../performance_tests:/app

networks:
  performance-demo-net:
